### ISSUE TITLE
transformer\datasets\IWSLT17中download.py的错误

### ISSUE THREAD

**Issue by co-nexo** [Kami-chanw/SeekDeeper#2]
在prepare函数中，访问下载解压下来的数据文件，会报路径不存在的错误
with open(
    os.path.join(data_path, src), mode="r", encoding="utf-8"
) as src_file, open(
    os.path.join(data_path, tgt), mode="r", encoding="utf-8"
) as tgt_file:

这一段我把raw_dir（值为 ./）改成了data_path（值为f"./{src_lang}-{tgt_lang}"）

**Comment by Kamichanw** [comment]
我闲的蛋疼才写那个download.py，现在已经删了，直接从load_dataset加载就行，别管这玩意了，点个star吧
