### ISSUE TITLE
transformer/data.py iwslt2017-en-de batch问题

### ISSUE THREAD

**Issue by BUGERR** [Kami-chanw/SeekDeeper#4]
transformer/data.py line 36和line 90报错
huggingface iwslt2017 An example of 'validation' looks as follows.
{
    "translation": {
        "de": "Die nächste Folie, die ich Ihnen zeige, ist eine Zeitrafferaufnahme was in den letzten 25 Jahren passiert ist.",
        "en": "The next slide I show you will be  a rapid fast-forward of what's happened over the last 25 years."
    }
}
直接用['en']报错

**Comment by Kamichanw** [comment]
感谢你的反馈，已修复
