### ISSUE TITLE
module 'datasets' has no attribute 'load_dataset'

### ISSUE THREAD

**Issue by jacmule** [Kami-chanw/SeekDeeper#5]
transformer/data.py 
![image](https://github.com/user-attachments/assets/122e5188-f27d-4306-b84e-82be101e3035)

**Comment by PBlithe** [comment]
Hello, I encountered the same issue as you did. May I ask how you resolved it? Looking forward to your reply.

**Comment by jacmule** [comment]
> Hello, I encountered the same issue as you did. May I ask how you resolved it? Looking forward to your reply.

just `pip install datasets`
