### ISSUE TITLE
[HELP] Possible Function Missing Issues in Transformer Code

### ISSUE THREAD

**Issue by PBlithe** [Kami-chanw/SeekDeeper#6]
Thank you very much for providing such clear and understandable code, which greatly solves the problem for beginners who are at a loss when facing large frameworks. When running the Transformer code, I encountered the following issue and look forward to your reply:
 **AttributeError: module 'datasets' has no attribute 'load_dataset'**

This error is caused by the loading of load_dataset in data.py. I have searched through all the code in the project files and could not find the load_dataset function.
![image](https://github.com/user-attachments/assets/1c780756-e5e2-41f4-bf3c-671bf912ecf7)

**Comment by Kamichanw** [comment]
The `datasets` is a powerful library used to manage datasets, which is developed by Huggingface. [Official repo](https://github.com/huggingface/datasets), [Official website](https://huggingface.co/docs/datasets/index).
In your case, just run
```bash
pip install datasets
```

**Comment by PBlithe** [comment]
> The `datasets` is a powerful library used to manage datasets, which is developed by Huggingface. [Official repo](https://github.com/huggingface/datasets), [Official website](https://huggingface.co/docs/datasets/index). In your case, just run
> 
> ```shell
> pip install datasets
> ```
Thank you for your reply, the problem is resolved according to your advice 🌹
